# Generated by Django 3.1.5 on 2021-01-11 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=35)),
                ('vehicle_shape', models.CharField(max_length=15)),
                ('engine', models.CharField(max_length=15)),
                ('horsepower', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('year', models.IntegerField(verbose_name=django.core.validators.MaxLengthValidator(4))),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
